### ISSUE TITLE
Panic when opening lazygit

### ISSUE THREAD

**Issue by jdguzman** [jesseduffield/lazygit#106]
Tried opening lazygit on one of the repos I work with and got this

```
[03:06:15] jdg ~/dev…polymer/polymer ᚴ [mainline] $ lazygit
panic: 15:8: unquoted '\' must be followed by new line

goroutine 1 [running]:
main.setupWorktree()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:93 +0x145
main.main()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:114 +0xd2
```

**Comment by jdguzman** [comment]
@jesseduffield thanks! I had used git tower a while back on this repo and it was related to that. Still feels like there should be better support for something like that but I guess it's not really a lazygit issue.
