### ISSUE TITLE
Panic after first repo commit

### ISSUE THREAD

**Issue by jdguzman** [jesseduffield/lazygit#109]
I got the following panic after making an initial commit on a new git repo.

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.getSelectedFile(0xc4201fa000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100f4f9, 0xc42001d100)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/files_panel.go:93 +0x131
main.handleFileSelect(0xc4201fa000, 0xc4202421e0, 0x143ede7, 0x5)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/files_panel.go:157 +0x5f
main.newLineFocused(0xc4201fa000, 0xc4202421e0, 0x5, 0xc4202421e0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/view_helpers.go:73 +0x104
main.switchFocus(0xc4201fa000, 0xc420242780, 0xc4202421e0, 0xc4202421e0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/view_helpers.go:115 +0x1fa
main.returnFocus(0xc4201fa000, 0xc420242780, 0xc, 0xc420242780)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/view_helpers.go:97 +0x78
main.closeConfirmationPrompt(0xc4201fa000, 0xc420242780, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/confirmation_panel.go:32 +0x7d
main.wrappedConfirmationFunction.func1(0xc4201fa000, 0xc420242780, 0xc, 0xc420067e01)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/confirmation_panel.go:23 +0x38
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4201fa000, 0xc420242780, 0xc4202a3d88, 0x10fc8f9, 0x0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:659 +0xdd
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc4201fa000, 0xc4202a3d88, 0xc42011e380, 0xc420204000)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:623 +0x1b3
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4201fa000, 0xc420067d88, 0xc420067d80, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:428 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4201fa000, 0x0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:388 +0x2c0
main.run(0x0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/gui.go:274 +0x161
main.main()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:116 +0xd7
```

A subsequent commit seemed to work fine though.

**Comment by jesseduffield** [comment]
I'm not able to replicate this issue locally. Are you able to provide reproduction steps?

**Comment by jdguzman** [comment]
Well I can't seem to reproduce this again, I've reset that repo and started over and followed the same steps I did before and it all worked fine so I'm going to chalk it up to a random fluke.

GREAT little project BTW. I mainline use the command line because I can't be bothered to switch context to a gui but this works a charm. My only request would be to allow partial staging of files. Sometimes while going to commit I will want to break up the changes to a file into smaller logical chunks and I couldn't see of a way to do that with lazygit.

FYI you should setup a Patreon or something like that for this, I'd glady through a few pounds per month your way for working on this.
