### ISSUE TITLE
Searching commits in a branch panics

### ISSUE THREAD

**Issue by grossjohann** [jesseduffield/lazygit#1183]
**Describe the bug**
When searching the commits of a branch, lazygit panics.

**To Reproduce**
1. Clone the lazygit repo
2. Start lazygit; the Files panel is active
3. Hit `l` (lowercase L) key to go to the Local Branches panel, which (for me) displays just the master branch.  But it does not matter which branches are shown, it happens for every branch and every repo I've tried.
4. Hit Return to view commits of the master branch; the commits are shown in the Local Branches panel.
5. Hit `/` (slash) to start searching.  At the "search:" prompt, enter something that has a match.  (The bug does not happen if there is no match.)  I've used "diff" and "pull", both of which provoke the panic.

Lazygit now crashes and the terminal displays a panic; the beginning of which I show under "Screenshots".

Note: Searching works fine in the Commits panel.

**Expected behavior**
The first commit that matches the search is selected.  (Same behavior as in the Commits panel.)

**Screenshots**

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getSelectedBranch(...)
	/home/runner/work/lazygit/lazygit/pkg/gui/branches_panel.go:27
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleBranchSelect(0xc000240b00, 0xc000280f68, 0x1735678)
	/home/runner/work/lazygit/lazygit/pkg/gui/branches_panel.go:32 +0x1e5
```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Lazygit Version 0.25.1 from HomeBrew
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**

**Comment by Liberatys** [comment]
This does not panic for me? Maybe it was fixed since the report?

**Comment by grossjohann** [comment]
I can confirm this no longer happens.  Using 0.28.1 from HomeBrew on macOS Big Sur 11.4.  Closing the issue.

**Comment by Liberatys** [comment]
👍🏻
