### ISSUE TITLE
new branch not working

### ISSUE THREAD

**Issue by hubertba** [jesseduffield/lazygit#119]
Hello

I implemented branch delete ( PR is coming ) 
but after merge of current master I cannot add branches anymore :-(

errormsg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1347817]

goroutine 1 [running]:
main.createPromptPanel(0xc4201da000, 0xc4202142d0, 0xc420294570, 0x29, 0x0, 0x1461030, 0x1, 0xc420294570)
	/Users/hubertbaumgartner/Applications/lazygit/confirmation_panel.go:82 +0x1e7
main.handleNewBranch(0xc4201da000, 0xc4202142d0, 0x8, 0xc420115e01)
	/Users/hubertbaumgartner/Applications/lazygit/branches_panel.go:44 +0xc1
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4201da000, 0xc4202142d0, 0xc420115d88, 0x1106a49, 0x0, 0x0)
	/Users/hubertbaumgartner/go/src/github.com/jesseduffield/gocui/gui.go:659 +0xdd
github.com/jesseduffield/gocui.(*Gui).onKey(0xc4201da000, 0xc420115d88, 0xc4201fa1c0, 0xc4201e4000)
	/Users/hubertbaumgartner/go/src/github.com/jesseduffield/gocui/gui.go:623 +0x1b3
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4201da000, 0xc420115d88, 0xc420115d80, 0x0)
	/Users/hubertbaumgartner/go/src/github.com/jesseduffield/gocui/gui.go:428 +0x40
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4201da000, 0x0, 0x0)
	/Users/hubertbaumgartner/go/src/github.com/jesseduffield/gocui/gui.go:388 +0x2c0
main.run(0x0, 0x0)
	/Users/hubertbaumgartner/Applications/lazygit/gui.go:276 +0x167
main.main()
	/Users/hubertbaumgartner/Applications/lazygit/main.go:118 +0xd7

**Comment by hubertba** [comment]
solved
