### ISSUE TITLE
Cannot change tabs on Windows

### ISSUE THREAD

**Issue by banjo** [jesseduffield/lazygit#1353]
**Describe the bug**
I cannot change tabs, Lazygit only crashes. This is on Windows 10, Lazygit 0.28.1. Git-bash and WSL. Installed from Scoop.

**To Reproduce**
Change tabs via the `x` menu.

**Expected behavior**
It should change tabs.

**Screenshots**
![example](https://i.imgur.com/zsTcO1Z.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Git bash and WSL2
 - Lazygit Version 0.28.1

**Additional context**
Error message:
```
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/utils.ModuloWithWrap(...)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:273
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleNextTab(0xc0001561c0, 0xc00011d380, 0xc0005fe010)
        /home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:368 +0x16a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleCreateOptionsMenu.func1(0xc0001561c0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/options_menu_panel.go:69 +0x79
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).onMenuPress(0xc0001561c0, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/menu_panel.go:101 +0x92
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).wrappedHandler.func1(0xc00011d380, 0xc000003e00, 0x88bf00, 0xc0003d58e0)
        /home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:314 +0x2d
github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc00011d380, 0xc000003e00, 0xc00035be40, 0x10100000000, 0x0, 0x2)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1167 +0x6d
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc00011d380, 0xc000003e00, 0xc0003d5900, 0xc00004c000, 0xc0003d58f0, 0xc000066780)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1135 +0x1d1
github.com/jesseduffield/gocui.(*Gui).onKey(0xc00011d380, 0xc0003d5900, 0xc00005ac10, 0xc000116200)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1060 +0x2ce
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc00011d380, 0xc0003d5900, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:651 +0x4d
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00011d380, 0xc000000004, 0xc0003f1a08)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:611 +0x1d8
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0001561c0, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:540 +0x51b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc0002f8001, 0xc0002d5aa0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:548 +0x48
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc0000a3b40, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:380 +0x67
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc0001561c0, 0x0, 0xfcd9d0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:547 +0x88
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002d79d0, 0xc0002be5a0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:242 +0x73
main.main()
        /home/runner/work/lazygit/lazygit/main.go:127 +0xb9b
```

**Comment by Krismix1** [comment]
From my testing it seems the problem only occurs when you try to switch the tab via the help menu. @banjo could you verify that if you use the `[` and `]` the tab is switched successfully?

If I try to switch to the previous tab using the menu option, I get a similar but a bit different error:
```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).onViewTabClick(...)
	github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:355
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePrevTab(0xc0000fa1c0, 0xc0002f8000, 0xc0002d4400)
	github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:378 +0x159
...
```
I think I have a fix for it, hope to open a PR for it tomorrow.

**Comment by banjo** [comment]
Unfortunately, changing tabs with `[` or `]` does not work for me as I have a Swedish keyboard layout. In Sweden, you access  `[` with `alt gr + 8`. When I do that, nothing happens. I also tried the shortcut that is used on a US keyboard, but nothing happens in that case as well. That is why I use the menu to change tabs. Maybe there is some way to change keybindings?

**Comment by karlovsek** [comment]
Hi, I get the same error.
To reproduce it, run lazygit, then press 1 (**Status** is selected) or 5 (**Stash** is selected) and then 'x' (the Menu opens), and then '[' or ']' -> crash.
OS: Linux, RHEL 7.4
Lazygit Version 0.35

`lazygit --version
commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=linux, arch=amd64`

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).onViewTabClick(...)
        /home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:126
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePrevTab(0xc000382b40)
        /home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:149 +0xf5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleCreateOptionsMenu.func1.1()
        /home/runner/work/lazygit/lazygit/pkg/gui/options_menu_panel.go:73 +0x26
github.com/jesseduffield/lazygit/pkg/gui/context.(*MenuContext).OnMenuPress(0x4d7a65?, 0xc000707560)
        /home/runner/work/lazygit/lazygit/pkg/gui/context/menu_context.go:135 +0x44
github.com/jesseduffield/lazygit/pkg/gui/context.(*MenuContext).GetKeybindings.func2.1()
        /home/runner/work/lazygit/lazygit/pkg/gui/context/menu_context.go:119 +0x25
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).SetKeybinding.func2(0x444f53?, 0x436796?)
        /home/runner/work/lazygit/lazygit/pkg/gui/keybindings.go:931 +0x1b
github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc00009b750?, 0x445daf?, 0xc00009b7a0?)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1302 +0x59
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0002be700, 0xc0001401e0, 0xc00009b7c0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1270 +0x530
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000761b0?, 0xc000142000?)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1146 +0xf1
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc00009b7a0?, 0xc00009b790?)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:697 +0x45
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002be700)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:657 +0x225
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000382b40, {{0x0?, 0x0?}, {0x0?, 0xc0003b39a0?}})
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:619 +0x6d6
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1()
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:625 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x0?)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:115 +0x67
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc000382b40, {{0x0?, 0xc0003de540?}, {0x0?, 0x18?}})
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:624 +0xc5
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(...)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:217
github.com/jesseduffield/lazygit/pkg/app.Run({0xcd3520?, 0xc0000d86e0?}, 0xc0003de540, {{0x0?, 0xba660e?}, {0x0?, 0xcc6218?}})
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:45 +0x92
main.main()
        /home/runner/work/lazygit/lazygit/main.go:154 +0xef0
```

**Comment by mark2185** [comment]
@karlovsek do you by any chance use a non-US keyboard layout?
