### ISSUE TITLE
Segfault during merge conflict (in bad state)

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1375]
**Describe the bug**

While merging on a project in a non-optimal state, lazygit will segfault during startup

```csharp
❯ lazygit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1599c88]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui/mergeconflicts.findConflicts(0xc0005f4000, 0x33b1, 0x10, 0x1da5688, 0x10)
        /home/runner/work/lazygit/lazygit/pkg/gui/mergeconflicts/find_conflicts.go:33 +0x108
github.com/jesseduffield/lazygit/pkg/gui/mergeconflicts.(*State).SetConflictsFromCat(0xc000280840, 0xc0005f4000, 0x33b1)
        /home/runner/work/lazygit/lazygit/pkg/gui/mergeconflicts/state.go:85 +0x39
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshMergePanel(0xc000152380, 0x1, 0xc000615760)
        /home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:163 +0x173
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).withMergeConflictLock(0xc000152380, 0xc0005bb530, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:312 +0x99
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshMergePanelWithLock(0xc000152380, 0xc00000af00, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:148 +0x4e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).selectFile(0xc000152380, 0xc000030100, 0xc000111cd8, 0x17ad888)
        /home/runner/work/lazygit/lazygit/pkg/gui/files_panel.go:71 +0x38e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).focusAndSelectFile(...)
        /home/runner/work/lazygit/lazygit/pkg/gui/files_panel.go:266
github.com/jesseduffield/lazygit/pkg/gui.(*ListContext).HandleFocus(0xc000123180, 0xc0000b7470, 0x5)
        /home/runner/work/lazygit/lazygit/pkg/gui/list_context.go:96 +0x178
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).activateContext(0xc000152380, 0x1860e78, 0xc000123180, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/context.go:248 +0x309
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).returnFromContext.func1(0xc000111ba0, 0xc0005bb7c0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/context.go:152 +0x13c
github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc000111ba0, 0xc0005bb900, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:637 +0x1a2
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000111ba0, 0xc000000004, 0xc00031fa08)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:619 +0x1ec
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000152380, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:540 +0x51b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc000272001, 0xc000126600)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:548 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00031fb40, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:118 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc000152380, 0x0, 0x177ed9f)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:547 +0x7d
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002ac460, 0xc00012e750, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:242 +0x6b
main.main()
        /home/runner/work/lazygit/lazygit/main.go:127 +0xb7b
```

**To Reproduce**

I saved a copy of my full git clone to reproduce, if the above error is not sufficient. Let me know if you'd like this and I'll email it across (may contain confidential information so don't want to post here).

**Screenshots**

![20210629 131745 (iTerm app)](https://user-images.githubusercontent.com/191335/123736632-6bec8700-d8dc-11eb-8e73-cc5820c5fbb8.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version commit=f91adf026bfbddc9505d6d84d3fabc80d49c7ca0, build date=2021-06-05T04:16:14Z, build source=binaryRelease, version=0.28.2, os=darwin, arch=amd64

**Comment by mjarkk** [comment]
@peppy can you confirm this is now fixed in the latest master?
