### ISSUE TITLE
Empty tag may crush lazygit

### ISSUE THREAD

**Issue by vbauerster** [jesseduffield/lazygit#1428]
This is sometimes reproducible bug. I caught it by submitting and empty tag by accident (T and then just enter).
```
panic: runtime error: index out of range [1] with length 1

goroutine 354 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc000157ef0, 0xc000178000, 0x4000, 0x4000)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/commands/loading_branches.go:56 +0x6c6
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc000157ef0, 0x0, 0x0, 0xc0000e21c0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/commands/loading_branches.go:97 +0x45
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches(0xc0000e21c0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/gui/branches_panel.go:71 +0xbe
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits.func1()
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/gui/commits_panel.go:85 +0x46
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x1006e75, 0xc00070e120)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/utils/utils.go:107 +0x24
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00038b7b8, 0x0, 0x0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/utils/utils.go:118 +0x62
github.com/jesseduffield/lazygit/pkg/utils.Safe(0xc000246000)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/utils/utils.go:107 +0x49
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/gui/commits_panel.go:82 +0xa8
```
Inspecting the repo with bare git revealed that malicious tag is named as commit hash. Reopening lazygit in the same repo panics again until I manually delete that tag.

If panic not happens inserting empty tag always goes to the latest commit, no matter where the cursor is.

**Comment by mjarkk** [comment]
Probably related to as it seem to crash on the same code: https://github.com/jesseduffield/lazygit/issues/1385  
This is probably fixed in the latest master tough no release with this fix yet.

**Comment by jesseduffield** [comment]
Closing as that fix is in v0.29
