### ISSUE TITLE
Panic: no changed file. Crash when executing "sublime"

### ISSUE THREAD

**Issue by Ronserruya** [jesseduffield/lazygit#15]
When i open lazygit and press on 's' (to open sublime) in crashes with this error:

```
panic: No changed files


goroutine 1 [running]:
log.Panicln(0xc42005df08, 0x1, 0x1)
	/home/ron/go1.9.2/src/log/log.go:340 +0xc0
main.run()
	/home/ron/go/src/github.com/jesseduffield/lazygit/gui.go:325 +0x1de
main.main()
	/home/ron/go/src/github.com/jesseduffield/lazygit/main.go:68 +0xfc
```

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/commit/0aa587f55ad618cdc57878487d499c4dd28c7734
closing :)
