### ISSUE TITLE
Crashes when hitting backspace on a multiline commit message

### ISSUE THREAD

**Issue by screendriver** [jesseduffield/lazygit#1531]
**Describe the bug**

When I enter a new commit message with multiple lines (`option + enter` on my MacBook) and press the backspace key `lazygit` crashes with `panic: runtime error: index out of range [5] with length 0`

**To Reproduce**
1. Enter a commit message
2. Press `option + enter` to enter multiline commit messages
3. Press backspace

**Expected behavior**

I should be able to delete characters from a commit message.

**Screenshots**

When I press backspace now I see the error:

<img width="836" alt="Screenshot 2021-10-21 at 11 13 52" src="https://user-images.githubusercontent.com/149248/138248549-d3c62d69-a481-4ca3-b8f3-f1a89af65340.png">

**Desktop (please complete the following information):**

 - OS: macOS 11.6
 - Lazygit Version `0.29`

```
✗ lg --version
commit=, build date=, build source=homebrew, version=0.29, os=darwin, arch=amd64
```

**Additional context**

Full error message:

```sh
panic: runtime error: index out of range [5] with length 0

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).EditDelete(0xc000217860, 0x17aad01)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/vendor/github.com/jesseduffield/gocui/edit.go:179 +0x337
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).commitMessageEditor(0xc0001ce000, 0xc000217860, 0x17007f, 0xc000170000, 0x104982c)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/pkg/gui/editors.go:20 +0xa5
github.com/jesseduffield/gocui.EditorFunc.Edit(0xc000204120, 0xc000217860, 0x7f, 0x1010a1a0000, 0x0)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/vendor/github.com/jesseduffield/gocui/edit.go:29 +0x4c
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0001d6000, 0xc000217860, 0xc000175900, 0xc000000180, 0xc0001758f0, 0xc000180a20)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/vendor/github.com/jesseduffield/gocui/gui.go:1152 +0x2bf
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0001d6000, 0xc000175900, 0xc000190350, 0xc00021c000)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/vendor/github.com/jesseduffield/gocui/gui.go:1063 +0x2c5
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0001d6000, 0xc000175900, 0x0, 0x0)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/vendor/github.com/jesseduffield/gocui/gui.go:654 +0x46
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0001d6000, 0xc000000004, 0xc00039fa08)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/vendor/github.com/jesseduffield/gocui/gui.go:614 +0x1c5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0001ce000, 0x0, 0x0)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/pkg/gui/gui.go:523 +0x51b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc0002f2a01, 0xc0001d4000)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/pkg/gui/gui.go:531 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00039fb40, 0x0, 0x0)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/pkg/utils/utils.go:126 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc0001ce000, 0x0, 0x17ac428)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/pkg/gui/gui.go:530 +0x7d
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000312540, 0xc0002ba870, 0x0)
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/pkg/app/app.go:240 +0x6b
main.main()
	/private/tmp/lazygit-20210817-6185-ly0x9c/lazygit-0.29/main.go:127 +0xb7b
```

**Comment by cice** [comment]
same here 👍 (same os and version)
