### ISSUE TITLE
Crash when deleting untracked file on Windows

### ISSUE THREAD

**Issue by chrislewisdev** [jesseduffield/lazygit#165]
First off, thanks for the awesome tool :)

**Describe the bug**
Every time I try to delete an untracked file with Lazygit on Windows, it crashes with the following error:

```
panic:

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleFileRemove.func1(0xc0421fa000, 0xc042238870, 0xc04205a2a0, 0xc04205a2a0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:130 +0xbc
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc0421fa000, 0xc042238870, 0xc, 0xc042055d01)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/confirmation_panel.go:20 +0x86
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0421fa000, 0xc042238870, 0xc042055d48, 0x516632, 0x0, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:662 +0xe4
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc0421fa000, 0xc042055d48, 0xc04209c0a0, 0xc042056160)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:626 +0x1ba
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0421fa000, 0xc042055d48, 0xc042055d40, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:431 +0x47
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0421fa000, 0xc0421fa000, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:391 +0x2eb
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc042073a40, 0x0, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:301 +0x261
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc042073a40)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:310 +0x36
main.main()
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:69 +0x1d8
```

**To Reproduce**
1. Add a new untracked file to your repository, e.g. `text.txt`
2. Open Lazygit
3. Highlight `text.txt` 
4. Press 'd' to delete the file and confirm
5. See error
6. The file will still be sitting in the repository

**Expected behavior**
The file should get deleted without error.

**Desktop:**
 - OS: Windows
 - Terminal: Powershell via integrated VS Code terminal. Issue occurs in standard cmd window also.
 - Lazygit Version: v0.1.61

**Additional context**
I've tried to check for anything preventing file deletion, e.g. it currently being open in an editor, but this occurs even when the file is not being used. It can be successfully deleted by traditional means.

**Comment by jesseduffield** [comment]
Could you pull down the latest master and see if the issue still appears? If you've installed via a binary, I'm deploying v0.1.64 now which should resolve the issue :)

**Comment by chrislewisdev** [comment]
Yep, that new binary version works! Legend 👍
