### ISSUE TITLE
Interactive rebase with a break prevents lazygit from startup

### ISSUE THREAD

**Issue by wolfgangwalther** [jesseduffield/lazygit#1759]
**Describe the bug**
Lazygit chokes on an interactive rebase with a break in the todo list.

**To Reproduce**
1. Start interactive rebase with `git rebase -i main`
2. Add two breaks anywhere
3. Start the rebase
4. Start lazygit - will crash immediately.

**Expected behavior**
No crash!

**Stacktrace**
```
panic: runtime error: slice bounds out of range [2:1]

goroutine 83 [running]:
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*CommitLoader).getInteractiveRebasingCommits(0xc0000bf590)
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/loaders/commits.go:320 +0x44b
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*CommitLoader).getRebasingCommits(0xbdcc28, 0xc000202120)
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/loaders/commits.go:244 +0x4f
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*CommitLoader).getHydratedRebasingCommits(0xc0000bf590, 0xaeb365)
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/loaders/commits.go:194 +0x33
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*CommitLoader).MergeRebasingCommits(0xc0000bf590, {0x109ee90, 0x0, 0x0})
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/loaders/commits.go:145 +0x14b
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*CommitLoader).GetCommits(0xc0000bf590, {0x1, {0x0, 0x0}, 0x1, {0xaeb551, 0x4}, 0x0})
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/loaders/commits.go:78 +0xdf
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommitsWithLimit(0xc00000c3c0)
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:119 +0x1a5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits.func2()
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:94 +0x2f
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1()
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:95 +0x1b
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x0)
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:106 +0x67
github.com/jesseduffield/lazygit/pkg/utils.Safe(0x0)
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:95 +0x35
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits
	/tmp/makepkg/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:93 +0x167
```

**Desktop:**
 - OS: Arch Linux
 - Lazygit Version: commit=d13a6481, build date=20220128.090800, build source=unknown, version=v0.32.1.d13a6481, os=linux, arch=amd64

**Additional context**
The same thing happens when running lazygit and then doing the same rebase on a different terminal. Lazygit will then crash on the next refresh.

**Comment by fsmiamoto** [comment]
Interesting, the culprit of this bug seems to be that we assume that lines in the `git-rebase-todo` match the pattern
`<action> <sha> <commit-msg>`:
```go
splitLine := strings.Split(line, " ")
commits = append([]*models.Commit{{
	Sha:    splitLine[1],
	Name:   strings.Join(splitLine[2:], " "),
	Status: "rebasing",
	Action: splitLine[0],
}}, commits...)
```
https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/loaders/commits.go#L317

This may not be true for a bunch of cases, as shown in the example:
```
pick deadbee Implement feature XYZ
fixup f1a5c00 Fix to feature XYZ
exec make
pick c0ffeee The oneline of the next commit
break
edit deadbab The oneline of the commit after
squash deadbaf Squasssshhh
rename beefdea Renamed commit
drop beefdaa Oops
exec cd subdir; make test
```

So to really fix this we would have to do a proper parsing of the `todo` file grammar:
```
Commands:
p, pick <commit> = use commit
r, reword <commit> = use commit, but edit the commit message
e, edit <commit> = use commit, but stop for amending
s, squash <commit> = use commit, but meld into previous commit
f, fixup [-C | -c] <commit> = like "squash" but keep only the previous
                   commit's log message, unless -C is used, in which case
                   keep only this commit's message; -c is same as -C but
                   opens the editor
x, exec <command> = run command (the rest of the line) using shell
b, break = stop here (continue rebase later with 'git rebase --continue')
d, drop <commit> = remove commit
l, label <label> = label current HEAD with a name
t, reset <label> = reset HEAD to a label
m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
.       create a merge commit using the original merge commit's
.       message (or the oneline, if no original merge commit was
.       specified); use -c <commit> to reword the commit message
```

If we think implementing the parsing is worth it, I'd love to take a stab at it :D

**Comment by wolfgangwalther** [comment]
Ah, good to know. That will likely make it break when using `exec`, too. That's something I didn't try with lazygit running, yet, but every now and then I have some complex rebase todo files including lots of `exec ...` commands. Would be cool if that could be parsed properly to not cause any problems.

**Comment by fsmiamoto** [comment]
Just as an update on this one, I've been working on a git todo file parser so maybe we'll be able to use it to solve this issue:
https://github.com/fsmiamoto/git-todo-parser

**Comment by jesseduffield** [comment]
Very cool @fsmiamoto

**Comment by fsmiamoto** [comment]
Sorry for the inactivity, I was kinda busy lately :sweat_smile: 
@jesseduffield I've created a draft pull request with my proposed changes and it seems to do the trick, at least for the scenario described in this issue.
I'll try to add unit tests for it but let me know if you have any suggestions or concerns.
