### ISSUE TITLE
panic: pipe: too many open files

### ISSUE THREAD

**Issue by ginesr** [jesseduffield/lazygit#1888]
**Describe the bug**
app crashes with panic: pipe: too many open files

**To Reproduce**
is failing on a regular git repo

**Expected behavior**
to work

**Screenshots**
```
panic: pipe: too many open files

goroutine 1676 [running]:
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*BranchLoader).obtainBranches(0x140002a4f00, 0x0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/commands/loaders/branches.go:112 +0x56c
github.com/jesseduffield/lazygit/pkg/commands/loaders.(*BranchLoader).Load(0x140002a4f00, 0x14000856000, 0x1d1, 0x200, 0x1400024e1e0, 0x100af91e8, 0x1400012aea0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/commands/loaders/branches.go:52 +0x30
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches(0x1400024e1e0)
	/home/runner/work/lazygit/lazygit/pkg/gui/branches_panel.go:63 +0x54
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits.func1()
	/home/runner/work/lazygit/lazygit/pkg/gui/commits_panel.go:89 +0x40
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x1400012b4a0, 0x1400113d7b0)
	/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:95 +0x28
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x1400113d7b8, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:106 +0x5c
github.com/jesseduffield/lazygit/pkg/utils.Safe(0x14000796258)
	/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:95 +0x40
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits
	/home/runner/work/lazygit/lazygit/pkg/gui/commits_panel.go:86 +0xa0
```

**Desktop (please complete the following information):**
 - OS: macosx 
 - Lazygit Version 0,34
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**
worked on a small repo just fine, is there a limitation for big repos?

**Comment by mark2185** [comment]
Is it a public repo so we can try to reproduce?

**Comment by ginesr** [comment]
It is not public, is a private repo hosted in github with lots of branches and a good amount of file

**Comment by ginesr** [comment]
I was able to capture the screen before crash
![err](https://user-images.githubusercontent.com/681701/164537028-c26147d8-b824-4e5e-9aa6-fa992a0b9de7.jpeg)

**Comment by mark2185** [comment]
It's something, thanks!

**Comment by lougreenwood** [comment]
Recently I've noticed that opening lazygit sometimes seems to bog down my system, even after I close it (I use it in a toggleterm in nvim)

Today when updating some nvim plugins I got this error when I started to notice my system being slow and just after opening & closing lazygit: 

```Vim:E903: Process failed to start: too many open files: "/usr/bin/git"```

I'm working on a mono repo with 6 frontend apps, around 250k loc (not sure if that's small or large for lazygit...)

**Comment by Bhanukamax** [comment]
I'm getting a similar stack trace, for a different error though, but they could all be related somehow :thinking: 
And I don't get this error for a fresh clone of the same repository.

Stack trace:
![image](https://github.com/jesseduffield/lazygit/assets/8494781/68b36378-b122-4703-a7fc-e53943d59ed1)

Error:
![image](https://github.com/jesseduffield/lazygit/assets/8494781/8ae39be5-05fe-458d-be7b-d102a66e18f9)

**Comment by Bhanukamax** [comment]
> @Bhanukamax version of lazygit?

I'm using from git `master` branch, my copy was a bit old, now I pulled again and rebuild and tested, I still see the error and it's stuck on that screen and exits lazygit when pressed `q`.

**Comment by Bhanukamax** [comment]
I got my issue solved, it was because I had a branch with some extra space and some additional (probably non-utf-8, guessing from the error message) characters, which also caused some issues in some `ci` pipelines, lazy git error disappeared once I deleted that branch.
This is a user error, but I think it would be nice if it could also be handled on the application level.

**Comment by jesseduffield** [comment]
I think the issue is that we do a refresh when we render an error, so we end up in an infinite loop, and that's what causes the too many open files error.

**Comment by lougreenwood** [comment]
For what it's worth... for me, the issue ended up being a result of the anti virus installed on my company issued laptop. Specifically `carbon black cloud`, any time I did a git operation it would spike the `se_agent` process and CPU would go high, multiple git operations seemed to create a large backlog.
