### ISSUE TITLE
panic: runtime error when cancelling out of "enter path to filter by"  dialog popup

### ISSUE THREAD

**Issue by craigmac** [jesseduffield/lazygit#1973]
**Describe the bug**
Cancelling out of of the "enter path to filter by" menu with control-c crashes lazygit in 0.34.

**To Reproduce**
1. Open lazygit 0.34
2. Press C-s to bring up Filtering popup
3. Choose "enter path to filter by"
4. Press Control-C

**Expected behavior**
Close the dialog.

**Screenshots**
<img width="813" alt="Screen Shot 2022-06-01 at 8 54 55 AM" src="https://user-images.githubusercontent.com/7416158/171409181-36382e67-c3e2-47b5-bdad-d4c0a6a4d0ef.png">
screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Lazygit Version: 0.34

**Additional context**
Traceback:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1558610]

goroutine 16 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).defaultEditor.func1()
        /private/tmp/lazygit-20220317-49157-jb72ih/lazygit-0.34/pkg/gui/editors.go:81 +0x30
github.com/jesseduffield/lazygit/pkg/tasks.(*AsyncHandler).Do.func1()
        /private/tmp/lazygit-20220317-49157-jb72ih/lazygit-0.34/pkg/tasks/async_handler.go:37 +0x2f
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1()
        /private/tmp/lazygit-20220317-49157-jb72ih/lazygit-0.34/pkg/utils/utils.go:95 +0x1b
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x103e3e5)
        /private/tmp/lazygit-20220317-49157-jb72ih/lazygit-0.34/pkg/utils/utils.go:106 +0x67
github.com/jesseduffield/lazygit/pkg/utils.Safe(0x0)
        /private/tmp/lazygit-20220317-49157-jb72ih/lazygit-0.34/pkg/utils/utils.go:95 +0x35
created by github.com/jesseduffield/lazygit/pkg/tasks.(*AsyncHandler).Do
        /private/tmp/lazygit-20220317-49157-jb72ih/lazygit-0.34/pkg/tasks/async_handler.go:36 +0x11b
```

**Comment by craigmac** [comment]
@mark2185 confirmed fixed on master build, thank you!
