### ISSUE TITLE
Panic during merge (Windows 10, Powershell)

### ISSUE THREAD

**Issue by miho** [jesseduffield/lazygit#207]
Running lazygit in one terminal and a merge conflict (I was merging in a different terminal) and an attempt to refresh (`R` key) I get a panic in lazygit:

**To Reproduce**
1. Open lazygit inside a repository
2. perform a merge (with merge conflicts) in another terminal window
3. Refresh via `R` key in the lazygit terminal
4. See `panic` error in lazygit terminal (see screenshot below)

**Expected behavior**
Lazygit shoudn't panic

**Screenshots**
![image](https://user-images.githubusercontent.com/225266/44469094-01447880-a627-11e8-8de4-80f29b8e8dfd.png)

Text version of the output:

```
panic:

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).catSelectedFile(0xc0420e8b00, 0xc042276000, 0xc0423d9a67, 0xc0423d9a60, 0xc0423d9a50, 0xc0423d9a46)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:326 +0x282
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshMergePanel(0xc0420e8b00, 0xc042276000, 0xc04207d910, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/merge_panel.go:179 +0x54
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleFileSelect(0xc0420e8b00, 0xc042276000, 0xc0422a21e0, 0x5, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:190 +0x26b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).newLineFocused(0xc0420e8b00, 0xc042276000, 0xc0422a21e0, 0xc0422a21e0, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:87 +0xd7
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).switchFocus(0xc0420e8b00, 0xc042276000, 0x0, 0xc0422a21e0, 0x0, 0x6)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:143 +0x3fd
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).layout(0xc0420e8b00, 0xc042276000, 0x0, 0x32007800af5864)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:270 +0xef6
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).(github.com/jesseduffield/lazygit/pkg/gui.layout)-fm(0xc042276000, 0x542e91, 0xee0ee0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:331 +0x3b
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc0422441a0, 0xc042276000, 0x0, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:344 +0x37
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).flush(0xc042276000, 0xb691f4, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:453 +0xdf
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc042276000, 0xc042276000, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:367 +0x61
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0420e8b00, 0x0, 0x0)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:337 +0x277
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0420e8b00)
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:346 +0x36
main.main()
        /Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:48 +0x12d
PS C:\Users\miho\Documents\GitHub\VMF-Text>
```

**Desktop (please complete the following information):**
 - OS: Windows 10 (Powershell)
 - Lazygit Version v0.1.73

**Comment by and09** [comment]
i have panic without anything
normal repo and not start program
mac os x

```
$ lazygit 
panic: 18:16: unquoted '\' must be followed by new line

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).setupWorktree(0xc4201e9da0)
	/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:165 +0x16b
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).SetupGit(0xc4201e9da0)
	/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:38 +0x47
main.main()
	/go/src/github.com/jesseduffield/lazygit/main.go:47 +0x114
```

**Comment by antham** [comment]
@and09 could you open another issue please because it's not related to this problem and tell if it  works with another git repository ?

**Comment by jesseduffield** [comment]
@antham It probably doesn't need to be a panic. I think there is an underlying issue about the cursor being on e.g. line 10, then committing (meaning all the files go away) then when focus returns to the files panel, it tries to show the diff or cat of the selected file, but there is no selected file under the cursor, so things go wrong. I'll have a deeper look into this today hopefully

**Comment by jesseduffield** [comment]
@and09 your issue is likely due to a git config issue. See https://github.com/jesseduffield/lazygit/issues/121

**Comment by jesseduffield** [comment]
@miho this should be fixed in the latest release. Please let me know if your issue is still there :)

**Comment by miho** [comment]
Can't reproduce it anymore. Thanks for the fix!
