### ISSUE TITLE
panic: ... missing argument to repetition operator: `*`

### ISSUE THREAD

**Issue by nils-a** [jesseduffield/lazygit#2288]
**Describe the bug**
if I start `lazygit` in one of my repos, it crashes right upon start with the following message:

```text
panic: regexp: Compile(`*\/([\S]+)`): error parsing regexp: missing argument to repetition operator: `*`

goroutine 69 [running]:
regexp.MustCompile(0xc00078a330, 0xa, 0xc000637e88)
        /opt/hostedtoolcache/go/1.16.7/x64/src/regexp/regexp.go:311 +0x15f
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).GetRemotes(0xc000181920, 0x4d5c293638782820, 0x74666f736f726369, 0x7a415c734b445320, 0x32494c435c657275, 0x69675c6e6962775c)
        /home/runner/work/lazygit/lazygit/pkg/commands/loading_remotes.go:30 +0x367
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshRemotes(0xc0001ce380, 0x6562762e74, 0x72676f72505c3a43)
        /home/runner/work/lazygit/lazygit/pkg/gui/remotes_panel.go:43 +0x5e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels.func1.5.1()
        /home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:165 +0x31
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x32494c435c657275, 0x69675c6e6962775c)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:115 +0x2b
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc000111fb8, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:126 +0x67
github.com/jesseduffield/lazygit/pkg/utils.Safe(0xc000276cd0)
        /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:115 +0x50
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels.func1.5
        /home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:165 +0x85
```

**To Reproduce**

This is a local error on one of my repos. 
If I do a clean clone of the repo, the error goes away.
So, sadly, there is no way to reproduce this currently.

**Expected behavior**
lazygit starts without problems.

**Version info:**
```bash
> lazygit --version
commit=d1a8b05401ccda1e52215203139a252eb3be3b79, build date=2022-11-14T09:22:31Z, build source=binaryRelease, version=0.36.0, os=windows, arch=amd64, git version=2.38.1.windows.1
> git --version
git version 2.38.1.windows.1
```

**Additional context**
I'm perfectly fine with closing this issue, since I can not provide steps to reproduce.
However, I'd be willing to run some tests, to get to the bottom of this. (Alas, I don't know any *go*)

**Comment by jesseduffield** [comment]
Sounds like we need to escape something in the regex at `lazygit/pkg/commands/loading_remotes.go:30`

**Comment by nils-a** [comment]
Yes, there was some escaping missing. 

My repo has `git config --local remote.*.prune true` set. This leads to an entry in the config file that looks like this:

```ini
[remote "*"]
	prune = true
```

Which leads to lazygit (actually, probably it's *go-git*'s fault.) believing there is a remote named `*`.

I've created #2290 to address this.

**Comment by nils-a** [comment]
Fixed in https://github.com/jesseduffield/lazygit/commit/ffc2a6805a29dfb14203884f988419c465778d05
