### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by sundarv85** [jesseduffield/lazygit#278]
Using
```
> lazygit -v
commit=b2f8b8b3457177fb5e01c57d92c4c3674c754e99, build date=2018-08-09T05:24:50Z, version=0.1.45
```

Got the following panic
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.getSelectedFile(0xc4200fa120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100f4f9, 0xc42014ad30)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/files_panel.go:93 +0x131
main.handleFileSelect(0xc4200fa120, 0xc42020a1e0, 0x143ab28, 0x5)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/files_panel.go:157 +0x5f
main.newLineFocused(0xc4200fa120, 0xc42020a1e0, 0x5, 0xc42020a1e0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/view_helpers.go:73 +0x104
main.switchFocus(0xc4200fa120, 0xc42020a780, 0xc42020a1e0, 0xc42020a1e0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/view_helpers.go:115 +0x1fa
main.returnFocus(0xc4200fa120, 0xc42020a780, 0xc, 0xc42020a780)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/view_helpers.go:97 +0x78
main.closeConfirmationPrompt(0xc4200fa120, 0xc42020a780, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/confirmation_panel.go:32 +0x7d
main.wrappedConfirmationFunction.func1(0xc4200fa120, 0xc42020a780, 0xc, 0xc42021ce01)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/confirmation_panel.go:23 +0x38
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4200fa120, 0xc42020a780, 0xc4202bdd88, 0x10fc8f9, 0x0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:659 +0xdd
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc4200fa120, 0xc4202bdd88, 0xc4200f8280, 0xc42014a680)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:623 +0x1b3
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4200fa120, 0xc42021cd88, 0xc42021cd80, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:428 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4200fa120, 0x0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:388 +0x2c0
main.run(0x0, 0x0)
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/gui.go:260 +0x130
main.main()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:124 +0x10d
```

**Comment by sundarv85** [comment]
Done. Will check and keep you updated!
