### ISSUE TITLE
signal SIGSEGV: segmentation violation when switching to a submodule

### ISSUE THREAD

**Issue by tkuraku** [jesseduffield/lazygit#2894]
**Describe the bug**
When switching to a submodule I get a SIGSEV. Not always, but sometimes. It might be related an internally hosted repository? This is on Rocky 8 and Rocky 9.  CLI and Sublime Merge both have no problems

**To Reproduce**

- Switch to submodule
- - SIGSEGV

**Expected behavior**
Switch to submodule without crash

**Version info:**
v0.40.0 Linux x86_64

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0xa67b54]

goroutine 252 [running]:
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshTags(0xc000134400)
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:391 +0x34
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.7()
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:149 +0x1d
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.1.1({0x0?, 0x0?})
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:101 +0x1b
github.com/jesseduffield/gocui.(*Gui).onWorkerAux(0x82b220?, 0xc000aa6810?, {0xde5c70?, 0xc00087a1a0?})
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:678 +0x71
github.com/jesseduffield/gocui.(*Gui).OnWorker.func1()
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:665 +0x31
created by github.com/jesseduffield/gocui.(*Gui).OnWorker
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:664 +0xaa
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xa697b3]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshStatus(0xc000134400)
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:666 +0x173
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2()
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:175 +0xa97
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh(0xc000134400, {0x0, {0x0, 0x0, 0x0}, 0x1})
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:190 +0x3d7
github.com/jesseduffield/lazygit/pkg/gui.(*guiCommon).Refresh(0xc00067c002?, {0x0, {0x0, 0x0, 0x0}, 0x1})
    /home/runner/work/lazygit/lazygit/pkg/gui/gui_common.go:28 +0x48
github.com/jesseduffield/lazygit/pkg/gui.NewGui.func2()
    /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:483 +0x3f
github.com/jesseduffield/lazygit/pkg/gui/popup.(*PopupHandler).ErrorMsg(0xc0002d3c70, {0xc000297860, 0x9f})
    /home/runner/work/lazygit/lazygit/pkg/gui/popup/popup_handler.go:91 +0x229
github.com/jesseduffield/lazygit/pkg/gui/popup.(*PopupHandler).Error(0xc000994300?, {0xddeca0?, 0xc000b860a0?})
    /home/runner/work/lazygit/lazygit/pkg/gui/popup/popup_handler.go:81 +0x76
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*AppStatusHelper).WithWaitingStatus.func1.1.1()
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/app_status_helper.go:37 +0x31
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).onUIThread.func1(0xc00070d638)
    /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:853 +0x1b
github.com/jesseduffield/gocui.(*Gui).processEvent(0xc00029e9c0)
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:758 +0x150
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00029e9c0)
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:739 +0xa5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00014f8c0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
    /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:669 +0x5e5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1()
    /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:675 +0x4c
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x0?)
    /home/runner/work/lazygit/lazygit/pkg/utils/utils.go:108 +0x67
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc00014f8c0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
    /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:674 +0xd4
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(...)
    /home/runner/work/lazygit/lazygit/pkg/app/app.go:263
github.com/jesseduffield/lazygit/pkg/app.Run({0xdeb3f0?, 0xc0002b0b40?}, 0xc0002cc7b0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
    /home/runner/work/lazygit/lazygit/pkg/app/app.go:48 +0xe9
github.com/jesseduffield/lazygit/pkg/app.Start(0xc0001e3f30, {0x0, 0x0})
    /home/runner/work/lazygit/lazygit/pkg/app/entry_point.go:154 +0xd06
main.main()
    /home/runner/work/lazygit/lazygit/main.go:23 +0x9e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0xa69069]

goroutine 253 [running]:
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshRemotes(0xc000134400)
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:600 +0x69
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.8()
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:153 +0x1d
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.1.1({0xc000994300?, 0xc0009942a0?})
    /home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:101 +0x1b
github.com/jesseduffield/gocui.(*Gui).onWorkerAux(0x0?, 0x0?, {0xde5c70?, 0xc00087a1e0?})
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:678 +0x71
github.com/jesseduffield/gocui.(*Gui).OnWorker.func1()
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:665 +0x31
created by github.com/jesseduffield/gocui.(*Gui).OnWorker
    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:664 +0xaa
```

**Comment by mark2185** [comment]
Is this something that started with v0.40.0 or has it occurred before that as well?

**Comment by tkuraku** [comment]
This is the first time I have used lazygit this weekend. (It is really great by the way!).

I just tried with the previous version, v0.39.4,  and it just hung and became unresponsive, but didn't die. I couldn't kill it with CTRL-C either. Had to just close the terminal window.

Here is the debug log for v0.40.0
[development.log](https://github.com/jesseduffield/lazygit/files/12270826/development.log)

**Comment by tkuraku** [comment]
I have a reproducer. Clone this repository and try and and switch to the c or d repositories from lazygit. It might have something to do with the submodules being in subdirectories. the b submodules opens fine.

<https://gitlab.com/tkuraku/a>

**Comment by jesseduffield** [comment]
Thanks for the repro steps!

For posterity I had to clone that with `git clone --recurse-submodules` for it to work.

The issue is in https://github.com/jesseduffield/lazygit/blob/7847203d6e8e89d4f5dc52ac167a219b0bd69d5f/pkg/commands/git_commands/repo_paths.go#L190 where we assume the submodule will be directly under the `modules` directory in the repo directory. We need to either be smarter about how we identify that we're dealing with a submodule, or relax the constraint that the `.git` needs to point to the 'right' place

**Comment by jesseduffield** [comment]
This'll go out in v0.40.2

**Comment by tkuraku** [comment]
You are awesome.
