### ISSUE TITLE
Panic when pressing escape/enter while pushing/pulling

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#320]
**Describe the bug**
A panic when pressing escape or enter while pushing or pulling  
```
panic: unknown view
goroutine 97 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).closeConfirmationPrompt(0xc0002fc000, 0xc00033a000, 0x0, 0xc00005dfb0)
	/home/mjarkk/go/src/github.com/jesseduffield/lazygit/pkg/gui/confirmation_panel.go:30 +0x11e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).pullFiles.func1(0xc0002fc000, 0xc00033a000)
	/home/mjarkk/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:349 +0xb2
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).pullFiles
	/home/mjarkk/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:345 +0xb5
```

**To Reproduce**
1. Open `lg`
2. Press <kbd>p</kbd>
3. When the popup pops up press <kbd>esc</kbd>

**Expected behavior**
Close popup or have no key bindings bind to the popup

**Screenshots**
![image](https://user-images.githubusercontent.com/15320763/47950720-8bc62400-df56-11e8-877b-2280362e1d07.png)

**Desktop (please complete the following information):**
 - OS: Linux, Fedora 29, 4.18.16-300.fc29.x86_64
 - Lazygit Version: Latest commit from jesseduffield/lazygit:master

**Additional context**
This is probably because of this function: [confirmation_panel.go#L139](https://github.com/jesseduffield/lazygit/blob/bf45e5b0e318defafedb4b6e0cda327b053c02bd/pkg/gui/confirmation_panel.go#L139), This function gets called at the end of the push and pull functoins

**Comment by mjarkk** [comment]
This issue is now fixed: https://github.com/jesseduffield/lazygit/pull/309
