### ISSUE TITLE
SIGSEGV github.com/jesseduffield/lazygit/pkg/commands/models.(*RemoteBranch).FullName(0xc0009afc20?)

### ISSUE THREAD

**Issue by jorgheymans** [jesseduffield/lazygit#3661]
In my terminal, i did `git checkout main && git pull --prune origin` on the repository that lazygit was open at in another terminal and it crashed. There were about 20 branches pruned in the pull, maybe this is what caused the problem ? Unsure how to correctly title this issue, feel free to change it.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fe4ae]

goroutine 473546 [running]:
github.com/jesseduffield/lazygit/pkg/commands/models.(*RemoteBranch).FullName(0xc0009afc20?)
	/home/runner/work/lazygit/lazygit/pkg/commands/models/remote_branch.go:10 +0xe
github.com/jesseduffield/lazygit/pkg/gui/context.NewRemoteBranchesContext.func3.GetRemoteBranchListDisplayStrings.1(0x0, 0xc000c32740?)
	/home/runner/work/lazygit/lazygit/pkg/gui/presentation/remote_branches.go:12 +0x2a
github.com/samber/lo.Map[...]({0xc000e35590?, 0x2, 0xe5c2a0}, 0xc0009afcb8?)
	/home/runner/work/lazygit/lazygit/vendor/github.com/samber/lo/slice.go:29 +0x74
github.com/jesseduffield/lazygit/pkg/gui/presentation.GetRemoteBranchListDisplayStrings(...)
	/home/runner/work/lazygit/lazygit/pkg/gui/presentation/remote_branches.go:11
github.com/jesseduffield/lazygit/pkg/gui/context.NewRemoteBranchesContext.func3(0x0?, 0x0?)
	/home/runner/work/lazygit/lazygit/pkg/gui/context/remote_branches_context.go:32 +0xa5
github.com/jesseduffield/lazygit/pkg/gui/context.(*ListRenderer).renderLines(0xc0002a1790, 0xffffffffffffffff, 0xffffffffffffffff)
	/home/runner/work/lazygit/lazygit/pkg/gui/context/list_renderer.go:88 +0x1b1
github.com/jesseduffield/lazygit/pkg/gui/context.(*ListContextTrait).HandleRender(0xc0002a1780)
	/home/runner/work/lazygit/lazygit/pkg/gui/context/list_context_trait.go:96 +0x45
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).postRefreshUpdate(0xc00029a608, {0xe627a8, 0xc000018408})
	/home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:140 +0xc7
github.com/jesseduffield/lazygit/pkg/gui.(*guiCommon).PostRefreshUpdate(0xc0008023d0?, {0xe627a8?, 0xc000018408?})
	/home/runner/work/lazygit/lazygit/pkg/gui/gui_common.go:33 +0x25
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshView(0xc0008a2580, {0xe627a8, 0xc000018408})
	/home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:736 +0x4c
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshRemotes(0xc0008a2580)
	/home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:661 +0x19f
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.9()
	/home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:164 +0x17
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.1.1({0x0?, 0x25?})
	/home/runner/work/lazygit/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:108 +0x13
github.com/jesseduffield/gocui.(*Gui).onWorkerAux(0xc0002c4700, 0x44695d?, {0xe54e38?, 0xc00032ac80?})
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:682 +0x6b
github.com/jesseduffield/gocui.(*Gui).OnWorker.func1()
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:669 +0x2b
created by github.com/jesseduffield/gocui.(*Gui).OnWorker in goroutine 1
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:668 +0x92
```

**Comment by goyalyashpal** [comment]
JD: github.com/jesseduffield
GLPK: github.com/jesseduffield/lazygit/pkg

```console
$ lazygit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa2dedf]

goroutine 1 [running]:
GLPK/commands/models.(*RemoteBranch).FullName(...)
	GLPK/commands/models/remote_branch.go:10
GLPK/gui/context.NewRemoteBranchesContext.func3.GetRemoteBranchListDisplayStrings.1(...)
	GLPK/gui/presentation/remote_branches.go:12
github.com/samber/lo.Map[...](...)
	github.com/samber/lo@v1.31.0/slice.go:29
GLPK/gui/presentation.GetRemoteBranchListDisplayStrings(...)
	GLPK/gui/presentation/remote_branches.go:11
GLPK/gui/context.NewRemoteBranchesContext.func3(0xc0000d4ca0?, 0xc000305138?)
	GLPK/gui/context/remote_branches_context.go:32 +0xbf
GLPK/gui/context.(*ListRenderer).renderLines(0xc0000d1a50, 0xffffffffffffffff, 0xffffffffffffffff)
	GLPK/gui/context/list_renderer.go:93 +0x1b1
GLPK/gui/context.(*ListContextTrait).HandleRender(0xc0000d1a40)
	GLPK/gui/context/list_context_trait.go:108 +0x117
GLPK/gui.(*Gui).postRefreshUpdate(0xc0003a0008, {0x1022ea0, 0xc000010990})
	GLPK/gui/view_helpers.go:135 +0x9b
GLPK/gui.(*guiCommon).PostRefreshUpdate(0x17595e0?, {0x1022ea0?, 0xc000010990?})
	GLPK/gui/gui_common.go:33 +0x25
GLPK/gui/controllers.(*RemotesController).enter(0xc000010d50, 0xc0001169c0)
	GLPK/gui/controllers/remotes_controller.go:130 +0x1d7
GLPK/gui/controllers.(*RemotesController).GetKeybindings.(*ListControllerTrait[...]).withItem.func1()
	GLPK/gui/controllers/list_controller_trait.go:116 +0x3b
GLPK/gui.(*Gui).callKeybindingHandler(0xc0003a0008, 0xc000517cc0?)
	GLPK/gui/keybindings.go:468 +0x10a
GLPK/gui.(*Gui).SetKeybinding.func1()
	GLPK/gui/keybindings.go:413 +0x1b
GLPK/gui.(*Gui).SetKeybinding.(*Gui).wrappedHandler.func3(0x0?, 0xc000305520?)
	GLPK/gui/keybindings.go:407 +0x13
JD/gocui.(*Gui).execKeybinding(0xc000305460?, 0x41af14?, 0xc00030556c?)
	JD/gocui@v0.3.1-0.20250220081214-b376cb0857ac/gui.go:1553 +0x4a
JD/gocui.(*Gui).execKeybindings(0xc0003aa000, 0xc000183208, 0xc000305580)
	JD/gocui@v0.3.1-0.20250220081214-b376cb0857ac/gui.go:1521 +0x418
JD/gocui.(*Gui).onKey(0xc0000d38b8?, 0xc000305508?)
	JD/gocui@v0.3.1-0.20250220081214-b376cb0857ac/gui.go:1328 +0x4d
JD/gocui.(*Gui).handleEvent(0xc0000d3890?, 0xc000305568?)
	JD/gocui@v0.3.1-0.20250220081214-b376cb0857ac/gui.go:845 +0x2f
JD/gocui.(*Gui).processEvent(0xc0003aa000)
	JD/gocui@v0.3.1-0.20250220081214-b376cb0857ac/gui.go:799 +0x226
JD/gocui.(*Gui).MainLoop(0xc0003aa000)
	JD/gocui@v0.3.1-0.20250220081214-b376cb0857ac/gui.go:778 +0xea
GLPK/gui.(*Gui).Run(0xc0003a0008, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
	GLPK/gui/gui.go:855 +0x525
GLPK/gui.(*Gui).RunAndHandleError.func1()
	GLPK/gui/gui.go:861 +0x48
GLPK/utils.SafeWithError(0xc00006b918?)
	GLPK/utils/utils.go:99 +0x56
GLPK/gui.(*Gui).RunAndHandleError(0xc0003a0008, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
	GLPK/gui/gui.go:860 +0xff
GLPK/app.(*App).Run(...)
	GLPK/app/app.go:270
GLPK/app.Run({0x101ab78?, 0xc000236160?}, 0xc000117e40, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}})
	GLPK/app/app.go:48 +0xda
GLPK/app.Start(0xc00006bf00, {0x0, 0x0})
	GLPK/app/entry_point.go:168 +0xd45
main.main()
	JD/lazygit/main.go:23 +0x98
[ble: exit 2][ble: elapsed 17m50s (CPU 35.2%)] lazygit

```

**Comment by goyalyashpal** [comment]
i faced the above crash too.

### steps:
1. open the local clone (i.e. my own one) of the upstream (https://github.com/NixOS/nixpkgs/) in terminal.  
2. open a new terminal tab, and run `lazygit` in it.
3. switch to shell tab, and run the following command (from the bash terminal tab) to try to clone and locally test this merge request https://github.com/NixOS/nixpkgs/pull/410240 .

	```console
	$ git remote add --track=cs50 --mirror=fetch cs50 https://github.com/amadejkastelic/nixpkgs.git
	
	```
4. this added the following snippet in the `.git/config` file of the repo:
	```properties
	[remote "cs50"]
		url = https://github.com/amadejkastelic/nixpkgs.git
		fetch = +refs/cs50:refs/cs50
	
	```

5. switch to lazygit tab, and go to branches panel - remotes `3]`, highlight the `cs50` remote (annotated with "0 branches")  and press enter 2-5 times.

### additional details

i didn't see the lazygit command log `@` while that happened, but now, it just shows the following:

```
Git output:
Fetching origin
Fetching upstream
Fetching cs50
fatal: couldn't find remote ref refs/cs50
error: could not fetch cs50 
```
