### ISSUE TITLE
Getting lazygit into Debian

### ISSUE THREAD

**Issue by jmkim** [jesseduffield/lazygit#385]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Package the lazygit and its dependencies into Debian.

**Describe alternatives you've considered**

**Additional context**
Hello,

I find out that @dawidd6 is making a lazygit package for Debian. I thought it would be great to have lazygit in Debian and its derivatives (not only Ubuntu :D).

I am an active Debian contributor and have done [some Debian packaging](https://qa.debian.org/developer.php?login=jmkim%40pukyong.ac.kr) with Go Packaging Team. I want to collaborate for releasing lazygit into Debian.

I already started packaging from v0.2.1 last year, when the features added very frequently and a lot of versions released in a day. From that time, I am monitoring this project and packaging a several dependencies. Still a lot of dependencies remaining (more than 48), so the time will take a lot I think.

lazygit Intent to Package bug report in Debian here: [1].
My packaging work for lazygit here: [2].

[1] https://bugs.debian.org/908894
[2] https://salsa.debian.org/go-team/packages/lazygit

**Comment by dawidd6** [comment]
Hi!

I've already replied to your email. I will happily cooperate with you on this.
It would be my first "official" packaging work for Debian, so I can lack some skills.

**Comment by jmkim** [comment]
@jesseduffield Could you please create a repository for Debian packaging work? It can be named like `lazygit-debian` or something.. And add us(@jmkim and @dawidd6) as a collaborator there please. Thank you!

I'll upload there a dependency graph, and we can discuss the packaging works in issue tracker there.

Very glad to co-work with you!

**Comment by dawidd6** [comment]
@jmkim or can't one of us just make a fork?

**Comment by jmkim** [comment]
As jesseduffield have a repository for releasing (homebrew), I thought it would be great that he create in his namespace. @jesseduffield ?

And I'm now updating my dependency trees to latest. After finish, let's start the packaging work.

**Comment by dawidd6** [comment]
Okay then, let's wait for what Jesse will say.

**Comment by jesseduffield** [comment]
Sounds like quite the undertaking! I've created the repo here: https://github.com/jesseduffield/lazygit-debian

I've invited you both as collaborators. Let me know if you need anything else from me :)

**Comment by jmkim** [comment]
@jesseduffield Cool! Very thanks a lot.

@dawidd6 I added dependency graph to [the wiki page on lazygit-debian](https://github.com/jesseduffield/lazygit-debian/wiki/Package-tracker), check out please! And let's move to [the issue tracker on lazygit-debian](https://github.com/jesseduffield/lazygit-debian/issues). Thank you!

**Comment by dawidd6** [comment]
@jmkim wow, that's a lot of good work you have done, with this graph, table and stuff. I'm starting my packaging.

**Comment by jmkim** [comment]
@jesseduffield Would you please make "Wiki" as public editable? More Debian people will come, and they should edit some wiki pages themselves. Thank you!

**Comment by jesseduffield** [comment]
Do you mean here or in the lazygit-debian repo?

**Comment by jmkim** [comment]
> Do you mean here or in the lazygit-debian repo?

lazygit-debian repo. Thank you!

**Comment by jesseduffield** [comment]
done :) (also I enabled it on this repo as well)

**Comment by jmkim** [comment]
:tada: :tada: 

Finally! lazygit is uploaded into Debian, and will be available to install with `apt install lazygit`, very shortly. I'll remind here when it available.

Almost of packaging jobs were processed by @dawidd6, so I want to give hime a lot of thanks. (Now he is looking forward to packaging the lazydocker ;) )

**Comment by jesseduffield** [comment]
awesome work @jmkim and @dawidd6 !

**Comment by dawidd6** [comment]
Yea, finally after almost half a year. Anyway good job @jmkim and thanks guys.

**Comment by glvr182** [comment]
I think this can be closed aswell

**Comment by ixzzd** [comment]
```
[I] ~ $ sudo apt update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                                 
Hit:3 http://deb.debian.org/debian buster-updates InRelease                         
Hit:4 https://download.docker.com/linux/debian buster InRelease                     
Hit:5 http://repository.spotify.com stable InRelease                                
Hit:6 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
[I] ~ $ sudo apt install lazygit
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lazygit
```

**Comment by rayluo** [comment]
@jmkim wrote this:

> Finally! lazygit is uploaded into Debian, and will be available to install with `apt install lazygit`, very shortly. I'll remind here again when it available.
> 
> https://ftp-master.debian.org/new/lazygit_0.8.1+ds.2-1.html
> 

Is it available now? I encounter similar issue as @ixzzd posted. Besides, there is no "lazygit" keyboard in this page either. https://ftp-master.debian.org/new/

(PS: For what it's worth, I'm using a distro named antix, which is a variant of Debian.)

**Comment by mariogrip** [comment]
Did this ever get accepted by the new queue? @jmkim

**Comment by jmkim** [comment]
Hi, @ixzzd @rayluo @mariogrip 

Sorry for my inactiveness for the triple years.
In my mailing archive, unfortunately, the package `lazygit` got REJECTED on Sep 7, 2019, due to the dependency.

```
Title: lazygit_0.8.1+ds.2-1_amd64.changes REJECTED

An exception was raised while processing the package:
Traceback (most recent call last):
  File "/srv/[ftp-master.debian.org/dak/dak/process_policy.py](http://ftp-master.debian.org/dak/dak/process_policy.py)", line 108, in wrapper
    function(upload, srcqueue, comments, transaction)
  File "/srv/[ftp-master.debian.org/dak/dak/process_policy.py](http://ftp-master.debian.org/dak/dak/process_policy.py)", line 221, in comment_accept
    extra_archives=[upload.target_suite.archive],
  File "/srv/[ftp-master.debian.org/dak/dak/daklib/archive.py](http://ftp-master.debian.org/dak/dak/daklib/archive.py)", line 449, in copy_binary
    self._ensure_extra_source_exists(filename, db_source, archive, extra_archives=extra_archives)
  File "/srv/[ftp-master.debian.org/dak/dak/daklib/archive.py](http://ftp-master.debian.org/dak/dak/daklib/archive.py)", line 243, in _ensure_extra_source_exists
    raise ArchiveException('{0}: Built-Using refers to package {1} (= {2}) not in target archive {3}.'.format(filename, source.source, source.version, archive.archive_name))
ArchiveException: l/lazygit/lazygit_0.8.1+ds.2-1_amd64.deb: Built-Using refers to package golang-github-ulikunitz-xz (= 0.5.5-1) not in target archive ftp-master.

Original comments:
```
Shamefully, I didn't take any action. It was due to very personal reason, very sorry for my inactiveness.
At that time, the package version was `0.8.1`. Now a lot of versions are came in.

I re-started the packaging with `0.40.2`.
I now estimated all the dependencies again, you can find [here](https://github.com/jesseduffield/lazygit-debian/wiki/Dependency-graph).

Could you please help me for re-open this issue? @jesseduffield @dawidd6
Could you please help me for packaging again? @dawidd6

There are 12 remaining dependencies and the lazygit itself.
Unvendoring and packaging is done on my local machine, so the dependencies are left.

**Comment by dawidd6** [comment]
Reopening, but I'm no longer interested in Debian packaging so I can't help. Maybe someone else will step up.

**Comment by jmkim** [comment]
Thanks. Now I am going on packaging the first dependencies of lazygit 0.40.2.

**Comment by WeepingClown13** [comment]
At the moment the installation would fail because of unsatisfiable dependency, but in a few hours it'll be solved once golang-github-ozeidan-fuzzy-patricia-dev is built by the Debian buildd machines.

**Comment by jmkim** [comment]
**Today, lazygit was uploaded to Debian testing.**

It will be included in **Debian 13 _"Trixie"_**, which will be released later this year.

I am closing this issue now. Once again, thanks to everyone who made this together.

**Comment by jesseduffield** [comment]
Great work @jmkim !
