### ISSUE TITLE
Lazy git segfaults on handleMouseDown

### ISSUE THREAD

**Issue by MaT1g3R** [jesseduffield/lazygit#567]
**Describe the bug**

Lazy git segfaults on rare occasions  

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9ed7bb]
goroutine 1 [running]:

github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleMouseDown(0xc4201f9b80, 0xc4202c0f20, 0xc420314500, 0x5a710c, 0xb957ae)
        github.com/jesseduffield/lazygit/pkg/gui/line_by_line_panel.go:183 +0x9b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).(github.com/jesseduffield/lazygit/pkg/gui.handleMouseDown)-fm(0xc4202c0f20, 0xc420314500, 0x2, 0xc4200c03b0)
        github.com/jesseduffield/lazygit/pkg/gui/keybindings.go:937 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc4202c0f20, 0xc420314500, 0xc4203800c0, 0xc4200ec0c0, 0xc4200ec120, 0xc4200ec0c0)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:832 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4202c0f20, 0xc420314500, 0xc4206f9b28, 0xc420314500, 0x0, 0x0)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:812 +0x19b
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc4202c0f20, 0xc4206f9b28, 0xc42030e0c0, 0xc4200c01f0)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:790 +0x1fc
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4202c0f20, 0xc4206f9b28, 0xc4206f9b20, 0x0)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:483 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4202c0f20, 0xc420121cc0, 0x1)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:443 +0x2f5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc4201f9b80, 0x0, 0x0)
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:822 +0x503
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc4201f9b80, 0xc420236cb0, 0xc420236c40)
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:831 +0x2f
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc420236b60, 0xc4201e8880, 0xc420236b60)
        github.com/jesseduffield/lazygit/pkg/app/app.go:166 +0x74
main.main()
        github.com/jesseduffield/lazygit/main.go:73 +0x6f3
```

**Expected behavior**

It does not Segfault

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Lazygit Version `commit=dab78c8, build date=2019-12-08, build source=debian, version=, os=linux, arch=amd64`

**Comment by jesseduffield** [comment]
This should be fixed in this PR https://github.com/jesseduffield/lazygit/pull/614
