### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference  

### ISSUE THREAD

**Issue by ndowens** [jesseduffield/lazygit#588]
**Describe the bug**
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                     546]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa69546]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*fileWatcher).watchingFilename(0x0, 0xc000026240, 0x27, 0xc000026240)
        /builddir/lazygit-0.12.3/pkg/gui/file_watching.go:39 +0x26
github.com/jesseduffield/lazygit/pkg/gui.(*fileWatcher).addFilesToFileWatcher(0x0, 0xc000010130, 0x1, 0x1, 0xc000010130, 0x1)
        /builddir/lazygit-0.12.3/pkg/gui/file_watching.go:84 +0x126
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshStateFiles(0xc0000a2280, 0xc51608, 0x5)
        /builddir/lazygit-0.12.3/pkg/gui/files_panel.go:358 +0xe8
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshFiles(0xc0000a2280, 0x0, 0x0)
        /builddir/lazygit-0.12.3/pkg/gui/files_panel.go:96 +0x103
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels(0xc0000a2280, 0xc0002b0210, 0x0, 0xc000378000)
        /builddir/lazygit-0.12.3/pkg/gui/view_helpers.go:20 +0x5a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).loadNewRepo(0xc0000a2280, 0xc52df3, 0x8)
        /builddir/lazygit-0.12.3/pkg/gui/gui.go:671 +0xc1
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).onInitialViewsCreation(0xc0000a2280, 0xc0002b0210, 0xc54b8e)
        /builddir/lazygit-0.12.3/pkg/gui/gui.go:661 +0xb2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).layout(0xc0000a2280, 0xc0002b0210, 0xc0000e2d58, 0xc000313a98)
        /builddir/lazygit-0.12.3/pkg/gui/gui.go:601 +0x128b
github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc0000d23e0, 0xc0002b0210, 0x0, 0x8)
        /builddir/lazygit-0.12.3/vendor/github.com/jesseduffield/gocui/gui.go:388 +0x30
github.com/jesseduffield/gocui.(*Gui).flush(0xc0002b0210, 0xc000313b80, 0x44576e)
        /builddir/lazygit-0.12.3/vendor/github.com/jesseduffield/gocui/gui.go:505 +0x33c
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002b0210, 0xc000000003, 0xc000313ce0)
        /builddir/lazygit-0.12.3/vendor/github.com/jesseduffield/gocui/gui.go:413 +0x54
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0000a2280, 0x0, 0x0)
        /builddir/lazygit-0.12.3/pkg/gui/gui.go:825 +0x506
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0000a2280, 0xc0001afa40, 0xc0001af9d0)
        /builddir/lazygit-0.12.3/pkg/gui/gui.go:834 +0x2f
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0001af880, 0xc000154980, 0xc0001af880)
        /builddir/lazygit-0.12.3/pkg/app/app.go:166 +0x6b
main.main()
        /builddir/lazygit-0.12.3/main.go:73 `+0x778`
```

**To Reproduce**
Update to 0.13 and launch lazygit

**Expected behavior**
Launch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazygit Version 0.13

**Comment by jesseduffield** [comment]
for whatever reason, it seems fsnotify is failing here. We swallow the error (and log it) but then another part of the code goes and tries calling functions on the file watcher. Interestingly you're allowed to do this even if the struct pointer is nil, so it's not until inside the function when trying to access a field of that struct that the error occurs. At any rate, I've switched from using a nil to represent that we're not file-watching, to a field called 'Disabled' and now you shouldn't see the crash.

Would still be interesting to know why fsnotify wasn't working though.

**Comment by jesseduffield** [comment]
see https://github.com/jesseduffield/lazygit/pull/594
