### ISSUE TITLE
Crash when checking out a remote branch

### ISSUE THREAD

**Issue by hffmnn** [jesseduffield/lazygit#730]
**Describe the bug**
Whenever I try to checkout a remote branch, the app crashes with the context described in the context section.

**To Reproduce**
1. Go to `Local Branches` (press `3`)
2. Go to `Remotes` (press `]`
3. Select your remote and press enter
4. Select the branch to check out and press `Space`
5. Crash

The `HEAD` is at the expected commit but the branch does not exist locally.

**Note:** I experienced this on a non-public gitlab repository. I tried to reproduce it with the lazygit repository without "success". Any idea how to track this down?

**Expected behavior**

A newly checked out local branch tracking the remote branch.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Lazygit Version 1.17.1

**Additional context**

```bash
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc000321998, 0xc0000ea97a, 0x20, 0xc0003800b8)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/pkg/commands/branch_list_builder.go:58 +0x4e3
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc000321998, 0xc000321aa0, 0xc00025c620, 0x3)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/pkg/commands/branch_list_builder.go:96 +0x6b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches.func1(0xc0001ac000, 0xc0003219e4, 0x3)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/pkg/gui/branches_panel.go:70 +0x52
github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc0001ac000, 0xc000321b38, 0x0)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/vendor/github.com/jesseduffield/gocui/gui.go:483 +0x1e8
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0001ac000, 0xc000000003, 0xc0003b1ca0)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/vendor/github.com/jesseduffield/gocui/gui.go:465 +0x215
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0001a4000, 0x0, 0x0)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/pkg/gui/gui.go:1010 +0x606
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0001a4000, 0x0, 0x0)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/pkg/gui/gui.go:1019 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc00025c4d0, 0xc000102a80, 0xc00025c4d0)
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/pkg/app/app.go:158 +0x6b
main.main()
	/private/tmp/lazygit-20200319-87001-fo2dtk/lazygit-0.17.1/main.go:67 +0x75a
```

**Comment by hffmnn** [comment]
Ok, got it:
A `git gc` gives

```bash
fatal: bad object refs/remotes/origin/HEAD
fatal: failed to run repack
```

Looks like the default branch changed since checking it out initially, editing `.git/refs/remotes/origin/HEAD` to point to a valid branch fixes this and I can also checkout a branch via lazygit.

Closing!
