### ISSUE TITLE
Crash when conflict occurs during rebase

### ISSUE THREAD

**Issue by GDYendell** [jesseduffield/lazygit#743]
**Describe the bug**

Lazygit crashed and won't re-open.

```
╔═[mef65357@pc0118 | /scratch/work/tools/RHEL7-x86_64/odin-data | 17:24]═|7.7|═|file-writing-metrics: *+$|REBASE-i 2/8|═■
╚═▶ lazygit 
panic: runtime error: slice bounds out of range [:8] with length 7

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui/presentation.getDisplayStringsForCommit(0xc0004bf4a0, 0x24, 0x24, 0xc00019c000)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/presentation/commits.go:125 +0xc50
github.com/jesseduffield/lazygit/pkg/gui/presentation.GetCommitListDisplayStrings(0xc000280300, 0x24, 0x30, 0xc0001d1000, 0x0, 0x0, 0xc0001d1080)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/presentation/commits.go:23 +0x97
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).renderBranchCommitsWithSelection(0xc000198480, 0xc0e11d, 0x7)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:551 +0xb6
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommitsWithLimit(0xc000198480, 0xc0003b6000, 0x0)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:110 +0x1b8
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits.func1(0xc0003b6000, 0xc00013b9e4, 0x3)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:78 +0x4f
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc0003b6000, 0x0, 0x0)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:483 +0x1e8
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0003b6000, 0xc000000003, 0xc0003c1ca0)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:465 +0x215
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000198480, 0x0, 0x0)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:1019 +0x606
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000198480, 0x0, 0x0)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:1028 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002fa4d0, 0xc0001b4a00, 0xc0002fa4d0)
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/pkg/app/app.go:158 +0x6b
main.main()
	/scratch/sw/go-apps/src/github.com/jesseduffield/lazygit/main.go:67 +0x75a
```

It gives the same error if I try to re-launch lazygit.

**To Reproduce**

I think it might have been caused by trying to amend a commit with staged changes causing a conflict. It happened a second time when I tried to manually complete the rebase where again there was a conflict, so maybe it can happen whenever there is a conflict during a rebase. It doesn't usually.

**Expected behavior**
I expected it to amend my commit and not crash.

**Desktop (please complete the following information):**
 - OS: RedHat Enterprise Linux 7.7
 - Lazygit Version: 3aab37611a26834af8348441d864ecad3eb15674 (I installed with `go get ...`)
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
The command above should be ```git rev-parse HEAD```

**Comment by GDYendell** [comment]
By the way, I have only been using this for a few days, but I think it is fantastic.

**Comment by jesseduffield** [comment]
glad to hear you're liking it! Could you try seeing if this PR fixes the issue? https://github.com/jesseduffield/lazygit/pull/745

**Comment by GDYendell** [comment]
![IMG_20200326_120702](https://user-images.githubusercontent.com/15689569/77645456-a7bad300-6f5a-11ea-8e60-3e2198ce2a60.jpg)
![IMG_20200326_120622](https://user-images.githubusercontent.com/15689569/77645473-ab4e5a00-6f5a-11ea-9f82-337995d95d70.jpg)

**Comment by GDYendell** [comment]
Thanks for the quick fix!

**Comment by jesseduffield** [comment]
no worries :)
