### ISSUE TITLE
My first try and it won't start. 

### ISSUE THREAD

**Issue by Dilapidus** [jesseduffield/lazygit#809]
**Topic**
I tapped the latest (brew install jesseduffield/lazygit/lazygit) and that got me 0.20.2

OSX 10.15.3

I'm in a folder that I've been working in for years.

~/dev/delerrok/touchpass : git status
On branch gtfs_tester
Your branch is up-to-date with 'origin/gtfs_tester'.
nothing to commit, working directory clean

When I run lazygit, this happens:  

```
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
└─────────────────────────────────────────────┘│                                                                                           │
┌─Local Branches - Remotes - Tags─────────────┐│                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                             ┌─Help make lazygit better──────────────────────────────────────────────────────┐                            │
│                             │Would you like to enable anonymous reporting data to help improve lazygit? (ent│                            │
│                             │er/esc)                                                                        │                            │
│                             └───────────────────────────────────────────────────────────────────────────────┘                            │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
└─────────────────────────────────────────────┘│                                                                                           │
┌─Commits - Reflog────────────────────────────┐│                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
│                                             ││                                                                                           │
└─────────────────────────────────────────────┘│                                                                                           │
┌─Stash───────────────────────────────────────┐│                                                                                           │
│                                             ││                                                                                           │
└─────────────────────────────────────────────┘└───────────────────────────────────────────────────────────────────────────────────────────┘
1-5: jump to panel, esc/q: close, pgup/pgdown: scroll, x: menu, ◄ ► ▲ ▼: navigatepanic: runtime error: index out of range [1] with length 12

goroutine 24 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc00032e778, 0x0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/commands/branch_list_builder.go:55 +0x60a
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc00009df78, 0x0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/commands/branch_list_builder.go:96 +0x43
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches(0xc000093450)
	/home/runner/work/lazygit/lazygit/pkg/gui/branches_panel.go:78 +0xb2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits.func1(0xc000093450, 0xc0000b46f0)
	/home/runner/work/lazygit/lazygit/pkg/gui/commits_panel.go:101 +0x39
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits
	/home/runner/work/lazygit/lazygit/pkg/gui/commits_panel.go:98 +0x79
~/dev/delerrok/touchpass : 
```
**Your thoughts**
This may be a bug, in which case I will happily rewrite the issue.  But I'm wondering what could be wrong here.

**Comment by Dilapidus** [comment]
I took a wee peek into the code.   The line being executed is a split output of a branch list:  

    git for-each-ref --sort=-committerdate --format="%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)" refs/heads

When I ran that my first line was this: 
> warning: ignoring broken ref refs/remotes/origin/HEAD

Which doesn't split as expected.   I'll fix my side and I imagine it will  work properly.   You might want to trap errors there.

**Comment by Dilapidus** [comment]
Yes..  that did it.  Specifically :
    git remote set-head origin master

I'll write a bug for handling of the error case if a committer requests it.
