### ISSUE TITLE
Starting lazygit in a git directory and pressing "p" rapidly causes a panic

### ISSUE THREAD

**Issue by ierdnah** [jesseduffield/lazygit#866]
**Describe the bug**
Lazygit panics if "p" is pressed immediately after starting.

**To Reproduce**
Start lazygit and then press rapidly "p". I think lazygit did not finish to initialize it's internal data and pressing "p" causes some kind of error.
➜  ansible2 git:(master) lazygit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa7d07f]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePullFiles(0xc000250a90, 0xc000270000, 0xc0000b29a0, 0x2, 0x100c00029fa08)
        github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:404 +0x4f
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:898
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc000270000, 0xc0000b29a0, 0xc00029fb08, 0xc000305aa0, 0xc000000208, 0xc0000002b8)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:891 +0x213
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc000270000, 0xc00029fb08, 0x2, 0x0)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:809 +0x281
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:497
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000270000, 0xc000000003, 0xc00029fc80)
        github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:457 +0x1f2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000250a90, 0x0, 0x0)
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:363 +0x65a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000250a90, 0x0, 0x0)
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:372 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc00018f420, 0xc0000cc980, 0x0)
        github.com/jesseduffield/lazygit/pkg/app/app.go:158 +0x6b
main.main()
        github.com/jesseduffield/lazygit/main.go:70 +0x811

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazygit Version commit=, build date=2020-05-19, build source=debian, version=0.20.4, os=linux, arch=amd64

**Comment by jesseduffield** [comment]
thanks for raising this issue, this makes it very easy to replicate the problem :) It looks like we have a concurrency issue that might call for a mutex
