### ISSUE TITLE
Merge Conflict panel exec: "type": executable file not found in %PATH% 

### ISSUE THREAD

**Issue by MikeVensel** [jesseduffield/lazygit#877]
**Describe the bug**
The merge conflicts panel displays an error saying, "exec: "type": executable file not found in %PATH%," rather than the merge conflict.

**To Reproduce**
1. Run a rebase that will produce a conflict.
2. Go to the files panel

**Expected behavior**
I would expect to see a typically conflict diff in the merge conflicts panel.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Lazygit Version v0.20.4

**Additional context**
Honestly this may just be something wrong in my environment but I am able to run the command `type test.txt` in cmd, in PowerShell with the command `cmd /c type test.txt` and in PowerShell directly with `type test.txt`. I am also able to run the command in the custom commands prompt in lazygit as well. I am able to open the file in VS Code and resolve the conflict but lazygit does not allow me to stage the file.

**Comment by rgwood** [comment]
I have the same issue on Windows 10 and lazygit 0.23.2.  Also if I hit space on the offending file in the files pane I get a crash:

```
panic: runtime error: index out of range [0] with length 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePickHunk(0xc00036a780, 0xc0002dad80, 0xc000470000, 0x1, 0xc0000879f0)                                                                                                                                                                                /home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:177 +0x1da
github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)                                                                                                                                                                                                                                                  /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:963
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0002dad80, 0xc000470000, 0xc00061a540, 0x48, 0x58, 0xc00061a540)                                                                                                                                                                                  /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:943 +0x1ac
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0002dad80, 0xc00061a540, 0xb1f040, 0xc00008c201)                                                                                                                                                                                                            /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:863 +0x2b9
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0002dad80, 0xc00061a540, 0x3, 0x0)                                                                                                                                                                                                                    /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x4d
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002dad80, 0xc000000004, 0xc0002cda98)                                                                                                                                                                                                                   /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:499 +0x402
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00036a780, 0x0, 0x0)                                                                                                                                                                                                                                /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:489 +0x4e9
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc00036a780, 0x0, 0xb4a008)                                                                                                                                                                                                           /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:502 +0x10b
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002bc070, 0xc0001d86c0, 0x0)                                                                                                                                                                                                                       /home/runner/work/lazygit/lazygit/pkg/app/app.go:230 +0x72
main.main()                                                                                                                                                                                                                                                                                                /home/runner/work/lazygit/lazygit/main.go:126 +0xb34
```

**Comment by murphy66** [comment]
I think #1133 solves this issue (I should've linked the pull request before, sorry).

**Comment by guban** [comment]
After upgrading to version 0.25, the problem persists, but the error message is now `The syntax of the command is incorrect.`

**Comment by naoey** [comment]
> 
> 
> After upgrading to version 0.25, the problem persists, but the error message is now `The syntax of the command is incorrect.`

In addition to this lazygit crashes if I try to stage the conflicted file after having resolved the conflict externally in my text editor. This is the resulting trace:
```
panic: runtime error: index out of range [0] with length 0                                                                                                                              goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePickHunk(0xc000240580, 0xc0000e8fc0, 0xc0000f6160, 0x1, 0xc0001a6320)                                                                     /home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:177 +0x1ea
github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)                                           /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:963
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0000e8fc0, 0xc0000f6160, 0xc00005ea20, 0x1692680, 0xc000044000, 0xc00028d948)                                                          /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:943 +0x1bd
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000e8fc0, 0xc00005ea20, 0x1692680, 0xc000093101)                                                                                                /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:863 +0x2dd
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0000e8fc0, 0xc00005ea20, 0x0, 0x0)             /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x4d
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000e8fc0, 0xc000000004, 0xc000161a90)            /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:499 +0x269
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000240580, 0x0, 0x0)                         /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:507 +0x525
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000240580, 0x0, 0x16bb13c)                                                                                               /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:520 +0x112
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000242310, 0xc0000e0630, 0x0)                /home/runner/work/lazygit/lazygit/pkg/app/app.go:240 +0x73
main.main()                                                                                         /home/runner/work/lazygit/lazygit/main.go:126 +0xb5b
```

This was using lazygit 0.26.2 on Windows 10 PowerShell.

**Comment by jesseduffield** [comment]
@naoey @guban @murphy66 @rgwood @MikeVensel the issue should be fixed in https://github.com/jesseduffield/lazygit/pull/1216 (admittedly I haven't been able to test the final product because something's gone wrong on my PC).

Let me know if the issue persists and I can re-open

**Comment by guban** [comment]
Now it works. Thanks!

**Comment by jesseduffield** [comment]
nice!

**Comment by MikeVensel** [comment]
Awesome thanks @jesseduffield!
