### ISSUE TITLE
panic: close of nil channel when TERM=alacritty

### ISSUE THREAD

**Issue by joshgummersall** [jesseduffield/lazygit#912]
**Describe the bug**
Running lazygit in Alacritty with the `TERM` environment variable set to `alacritty` causes a panic.

**To Reproduce**
1. Install [alacritty](https://github.com/alacritty/alacritty) and [configure terminfo](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo)
2. Ensure `TERM` environment variable is set to `alacritty`
3. Run `lazygit` inside a git repo

**Expected behavior**
Lazygit should run as expected

**Desktop (please complete the following information):**
 - OS: Linux, Pop!_OS 20.04
 - Lazygit Version: installed via `go get`, commit sha is `e82d2f37a108afbf4abbdcad9ab1da33f927836d`

**Additional context**
Running lazygit in the same environment, i.e. Alacritty, via `TERM=xterm-256color lazygit` works just fine. Here is the stack trace:
```
panic: close of nil channel

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0002c9860, 0x0, 0x0)
	/home/jpg/src/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:382 +0x115
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0001d9dc0, 0xc000126800, 0x0)
	/home/jpg/src/go/src/github.com/jesseduffield/lazygit/pkg/app/app.go:165 +0x6b
main.main()
	/home/jpg/src/go/src/github.com/jesseduffield/lazygit/main.go:70 +0x811
```

**Comment by joshgummersall** [comment]
I've always had luck running `lazygit` with `TERM=xterm lazygit` so I suspect it's roughly compatible, though I don't see any direct references to xterm in the [terminfo file](https://github.com/alacritty/alacritty/blob/master/extra/alacritty.info). I pasted some error output from running the test build [on the pull request](https://github.com/jesseduffield/lazygit/pull/955#issuecomment-678799178).

**Comment by joshgummersall** [comment]
Resolved! Thanks @jesseduffield
