### ISSUE TITLE
Reproducible segfault after trying to revert a chunk.

### ISSUE THREAD

**Issue by vigoux** [jesseduffield/lazygit#917]
**Describe the bug**
Lazygit segfaults after trying to revert a change and aborting.

**To Reproduce**
1. Make a change in you git repo
2. Hit `Enter` on the file you changed
3. Hit `d` to try deleting the change and escape to abort.
4. Hit `j` (or any key)
5. Segfault happens

**Expected behavior**

Hehe, no segfault.

**Screenshots**

Error message :
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa55f82]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).Origin(...)
        /builddir/lazygit-0.20.8/vendor/github.com/jesseduffield/gocui/view.go:368
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).scrollDownView(0xc0003985b0, 0xc24dc3, 0xc, 0x2, 0x100000000000d)
        /builddir/lazygit-0.20.8/pkg/gui/global_handlers.go:49 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).scrollDownConfirmationPanel(...)
        /builddir/lazygit-0.20.8/pkg/gui/global_handlers.go:102
github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
        /builddir/lazygit-0.20.8/vendor/github.com/jesseduffield/gocui/gui.go:898
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc00038e2d0, 0xc0003c2420, 0xc00018bb50, 0xc0000b4960, 0xc000000208, 0xc0000002b8)
        /builddir/lazygit-0.20.8/vendor/github.com/jesseduffield/gocui/gui.go:878 +0x18d
github.com/jesseduffield/gocui.(*Gui).onKey(0xc00038e2d0, 0xc00018bb50, 0x2, 0x0)
        /builddir/lazygit-0.20.8/vendor/github.com/jesseduffield/gocui/gui.go:809 +0x281
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
        /builddir/lazygit-0.20.8/vendor/github.com/jesseduffield/gocui/gui.go:497
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00038e2d0, 0xc000000003, 0xc0001e9c98)
        /builddir/lazygit-0.20.8/vendor/github.com/jesseduffield/gocui/gui.go:457 +0x1f2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0003985b0, 0x0, 0x0)
        /builddir/lazygit-0.20.8/pkg/gui/gui.go:363 +0x63a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0003985b0, 0x0, 0x0)
        /builddir/lazygit-0.20.8/pkg/gui/gui.go:372 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002d64d0, 0xc000100900, 0x0)
        /builddir/lazygit-0.20.8/pkg/app/app.go:165 +0x6b
main.main()
        /builddir/lazygit-0.20.8/main.go:70 +0x7f3
```

**Desktop (please complete the following information):**
 - OS: Void linux
 - Lazygit Version : 0.20.8 ? (latest void-linux version)

**Additional context**
Not related but there is still a bug when trying to open lazygit in a submodule you access through a symlink. Reported an error a while ago...

**Comment by jesseduffield** [comment]
hmm I'm unable to reproduce this locally. Is there a specific repo this happens on, or is it all repos?

**Comment by vigoux** [comment]
Yep, I tested this on an empty repo, trying to discard part of a newly added file, and was able to reproduce.
