### ISSUE TITLE
Panic after cancelling search in menu

### ISSUE THREAD

**Issue by macintacos** [jesseduffield/lazygit#976]
**Describe the bug**
When you press `x` to bring up the menu, hit `/` to search, and then hit `esc` until you back out to your shell, you're presented with a backtrace for the following panic:

```
 I => lazygit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1692df1]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).Name(...)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/view.go:297
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleSearchEscape(0xc0002dbd40, 0xc0002f41e0, 0xc00014fa20, 0x2, 0x1000000000000)
	/home/runner/work/lazygit/lazygit/pkg/gui/searching.go:89 +0x31
github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:909
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0002f41e0, 0xc00014fa20, 0xc000779b70, 0xc000533260, 0xc000000208, 0xc0000002b8)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:889 +0x19b
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0002f41e0, 0xc000779b70, 0x2, 0x0)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:809 +0x2af
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:497
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002f41e0, 0xc000000003, 0xc0001c9c98)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:457 +0x1f2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0002dbd40, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:454 +0x507
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0002dbd40, 0x0, 0xc00003a900)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:464 +0x74
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002d1b20, 0xc00003a900, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/app/app.go:179 +0x6b
main.main()
	/home/runner/work/lazygit/lazygit/main.go:70 +0x7f3
```

I can reliably reproduce this.

**To Reproduce**
1. Open `lazygit`
2. Press `x` to bring up the menu
3. Press `/` to begin searching (you don't have to start searching)
4. Press `esc` until you get to your shell

**Expected behavior**
Lazygit doesn't complain and panic.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Lazygit Version - commit=45a0378c01236af91451a1fbf14aa2e65561200b, build date=2020-08-25T22:22:25Z, build source=binaryRelease, version=0.22.1, os=darwin, arch=amd64

(installed just now via homebrew)

**Comment by jesseduffield** [comment]
Thanks for raising this, I was able to reproduce and https://github.com/jesseduffield/lazygit/pull/977 fixes it for me
