### ISSUE TITLE
lazygit crashes after searching keywords in menu

### ISSUE THREAD

**Issue by dzungtran89** [jesseduffield/lazygit#995]
**To Reproduce**
1. Press `x` to open menu
2. Press `/` and search any words
3. Press `esc` to exit search mode
4. Press `esc` again to quit the menu

**Expected behavior**
Continue working on lazygit

**Desktop (please complete the following information):**
 - OS: macos 10.15.6
 - Lazygit Version: 0.22.1

**Additional context**
Crash logs as below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b44d1]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).Name(...)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/vendor/github.com/jesseduffield/gocui/view.go:297
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleSearchEscape(0xc0002dfd40, 0xc0002f03c0, 0xc0000fd080, 0x2, 0x1000000000027)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/pkg/gui/searching.go:89 +0x31
github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/vendor/github.com/jesseduffield/gocui/gui.go:909
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0002f03c0, 0xc0000fd080, 0xc000487b70, 0xc000000208, 0xc000487b58, 0xc0000002b8)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/vendor/github.com/jesseduffield/gocui/gui.go:889 +0x1b1
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0002f03c0, 0xc000487b70, 0x2, 0x0)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/vendor/github.com/jesseduffield/gocui/gui.go:809 +0x2bd
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/vendor/github.com/jesseduffield/gocui/gui.go:497
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002f03c0, 0xc000000003, 0xc000273c98)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/vendor/github.com/jesseduffield/gocui/gui.go:457 +0x20a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0002dfd40, 0x0, 0x0)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/pkg/gui/gui.go:454 +0x52c
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0002dfd40, 0x0, 0xc00022a880)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/pkg/gui/gui.go:464 +0x76
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000306850, 0xc00022a880, 0x0)
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/pkg/app/app.go:179 +0x6b
main.main()
	/private/tmp/lazygit-20200826-5620-szew44/lazygit-0.22.1/main.go:70 +0x7e5
```

**Comment by mewejo** [comment]
I can reproduce on PopOS/Ubuntu too 20.04 too, Lazygit 0.22.1

I used to use an older version of Lazygit which was very stable, I upgraded a couple of weeks back and `0.22.1` has been very unstable for me. Random crashes/hangs etc, not sure if that's related to the crash here.

**Comment by jesseduffield** [comment]
Hmm, this has been fixed in v0.22.3, and the latest version is v0.22.4. Are those versions not available to you guys?

**Comment by jesseduffield** [comment]
just confirmed the latest version isn't in homebrew, damn! Will see how redeploying goes now

**Comment by dzungtran89** [comment]
Thanks alot for your hard work!

**Comment by mewejo** [comment]
Thanks Jesse! :) Just upgraded to 0.22.6

**Comment by dzungtran89** [comment]
Works like a charm, except another issue regarding to git version detect, someone reported it here [1005](https://github.com/jesseduffield/lazygit/issues/1005)

**Comment by jesseduffield** [comment]
I'm pushing a new release now to fix the git version check :)

**Comment by dzungtran89** [comment]
Upgraded and worked like a charm, thank you so much!
